name: Run Command in Codespace

on:
  schedule:
    # Runs every 3 hours
    - cron: '0 */3 * * *' 

jobs:
  run_command:
    runs-on: ubuntu-latest # Or your preferred runner image
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run command in Codespace
        run: |
          # Replace 'your_command_here' with the actual command you want to run.
          # Example: echo "Hello from Codespace!"
          # Example: npm run build
          say nigger

          echo Add other actions to build,
          echo test, and deploy your project.
