<<<<<<< HEAD:.github/workflow_dispatch.yml
    
=======
>>>>>>> refs/remotes/origin/main:.github/workflows/workflow_dispatch.yml
 on:
          workflow_dispatch:
            inputs:
              # Optional inputs for manual runs
              logLevel:
                description: 'Log level'
                required: true
                default: 'info'